version: '3'
services:

 store:
    build :
            context: ./custom_virtuoso
            dockerfile: Dockerfile
    image: virtuoso-opensource-custom_vad
    ports: ["${VIRTUOSO_HTTP_PORT}:8890","127.0.0.1:${VIRTUOSO_ISQL_PORT}:1111","127.0.0.1:${VIRT_HTTPSERVER_SSLPORT}:4443"]
    environment:
            DBA_PASSWORD: ${VIRTUOSO_ADMIN_PASSWD}
            VIRT_Parameters_DirsAllowed: ${VIRT_Parameters_DirsAllowed}
            VIRT_PARAMETERS_NUMBEROFBUFFERS: ${VIRT_PARAMETERS_NUMBEROFBUFFERS}
            VIRT_PARAMETERS_MAXDIRTYBUFFERS: ${VIRT_PARAMETERS_MAXDIRTYBUFFERS}
            VIRT_Client_SQL_UTF8_EXECS: ${VIRT_Client_SQL_UTF8_EXECS}
            VIRT_Parameters_MaxVectorSize: ${VIRT_Parameters_MaxVectorSize}
            VIRT_HTTPSERVER_SSLCERTIFICATE: ${VIRT_HTTPSERVER_SSLCERTIFICATE}
            VIRT_HTTPSERVER_SSLPRIVATEKEY: ${VIRT_HTTPSERVER_SSLPRIVATEKEY}
            VIRT_HTTPSERVER_X509CLIENTVERIFYCAFILE: ${VIRT_HTTPSERVER_X509CLIENTVERIFYCAFILE}
            VIRT_HTTPSERVER_X509CLIENTVERIFY: 1
            VIRT_HTTPSERVER_X509CLIENTVERIFY: 15
    restart: always
    volumes:
      - ${VIRTUOSO_DATABASE_DIR}:/opt/virtuoso-opensource/database
      - ${DATA_DIR}:/usr/share/proj
