version: '3'
services:

 store:
    build :
            context: ./custom_virtuoso
            dockerfile: Dockerfile
    image: virtuoso-opensource-custom_vad
    name: fr.dbpedia.org
    ports: ["${VIRTUOSO_HTTP_PORT}:8890","127.0.0.1:${VIRTUOSO_ISQL_PORT}:1111"]
    environment:
            DBA_PASSWORD: ${VIRTUOSO_ADMIN_PASSWD}
            VIRT_PARAMETERS_MAXSTATICCURSORROWS: ${VIRT_PARAMETERS_MAXSTATICCURSORROWS}
            VIRT_SPARQL_RESULTSETMAXROWS: ${VIRT_SPARQL_RESULTSETMAXROWS}
            VIRT_SPARQL_MAXQUERYCOSTESTIMATIONTIME: ${VIRT_SPARQL_MAXQUERYCOSTESTIMATIONTIME}
            VIRT_SPARQL_MAXQUERYEXECUTIONTIME: ${VIRT_SPARQL_MAXQUERYEXECUTIONTIME}
            VIRT_Parameters_DirsAllowed: ${VIRT_Parameters_DirsAllowed}
            VIRT_PARAMETERS_NUMBEROFBUFFERS: ${VIRT_PARAMETERS_NUMBEROFBUFFERS}
            VIRT_PARAMETERS_MAXDIRTYBUFFERS: ${VIRT_PARAMETERS_MAXDIRTYBUFFERS}
            VIRT_Client_SQL_UTF8_EXECS: ${VIRT_Client_SQL_UTF8_EXECS} 

            VIRT_PARAMETERS_MAXVECTORSIZE: ${VIRT_PARAMETERS_MAXVECTORSIZE}
            VIRT_HTTPSERVER_SERVERTHREADS: ${VIRT_HTTPSERVER_SERVERTHREADS}
            VIRT_HTTPSERVER_MAXCLIENTCONNECTION: ${VIRT_HTTPSERVER_MAXCLIENTCONNECTION}
            VIRT_HTTPSERVER_THREADSPERQUERY: ${VIRT_HTTPSERVER_THREADSPERQUERY}
            VIRT_HTTPSERVER_ASYNCQUEUEMAXTHREADS: ${VIRT_HTTPSERVER_ASYNCQUEUEMAXTHREADS}
            VIRT_PARAMETERS_MAXVECTORSIZE: ${VIRT_PARAMETERS_MAXVECTORSIZE}

    restart: always
    volumes:
      - ${VIRTUOSO_DATABASE_DIR}:/opt/virtuoso-opensource/database
      - ${DATA_DIR}:/usr/share/proj
